### ISSUE TITLE
Compile issue with Xcode 11.4

### ISSUE THREAD

**Issue by satyres** [veezee-music/veezee-ios#1]
Hi
i'm unable to compile your project with Xcode 11.4
many errors.
any hint please
regards

**Comment by vsg24** [comment]
I really can't support the iOS version anymore however you should be able to compile it using an older version of Xcode such as 11.2 also I remember that last time I compiled the project I used **JetBrains AppCode** as Xcode was throwing out stupid errors that shouldn't have happened so please give AppCode a try (It's free for 30 days)
