### ISSUE TITLE
getting errors for multiple pods errors

### ISSUE THREAD

**Issue by rehmantalha51** [veezee-music/veezee-ios#2]
Hi guys, I have tried your app but I am unable to compile as I am getting multiple error on the code I cloned 
I have latest Xcode (12.2) but i do get multiple errors on the base code, i did followed the instructions before building. see the screenshots

<img width="1511" alt="Screenshot 2020-11-28 at 1 46 30 PM" src="https://user-images.githubusercontent.com/41566412/100497963-9dec0e00-3180-11eb-83b1-d0fb882f769e.png">
<img width="1511" alt="Screenshot 2020-11-28 at 1 46 37 PM" src="https://user-images.githubusercontent.com/41566412/100497965-a3495880-3180-11eb-99da-ddfa3cf1081d.png">

However as I have some experience in iOS development i did update some pods to their latest version, removed derived data, updated pods repo and clean build the code and I am down to these 7 errors which I am unable to get rid of

<img width="1511" alt="Screenshot 2020-11-28 at 1 46 54 PM" src="https://user-images.githubusercontent.com/41566412/100497994-df7cb900-3180-11eb-941a-bb5f3dd6c847.png">
<img width="1511" alt="Screenshot 2020-11-28 at 1 47 05 PM" src="https://user-images.githubusercontent.com/41566412/100497997-e5729a00-3180-11eb-9f91-141e46298b57.png">

Any help from you guys is much appreciated

**Comment by vsg24** [comment]
It appears that some libraries used in the project are not compatible with the latest version of Xcode/iOS SDK. Unfortunately I don't have a macOS machine around me to mess with this project but I do recommend commenting out all lines using those libraries or replacing them with more up-to-date alternatives. That shouldn't be a lot of work.

**Comment by rehmantalha51** [comment]
Thank you for your response, I've managed to fix the issues but I am unable to test this because the app registration isn't working so is there any way you can provide me some demo credentials which I can login through and have a look at it, it would be nice to test it with your demo server... looking forward to it

**Comment by vsg24** [comment]
Actually the server application's source code has always been available [here](https://github.com/veezee-music/veezee-server-example). You can create a local server and test things out for yourself. Don't forget to modify API endpoint url in constants file in iOS app.
